name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle lock --add-platform x86_64-linux
    - run: bundle exec jekyll build -V
      env:
        CI: true
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
