name: CI

on: [push, pull_request]

jobs:
  test:
    name: Build the site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - run: sudo apt-get install -y bundler
    - run: bundle install --path vendor/bundle
    - run: bundle exec jekyll build -V
      env:
        CI: true
    - uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site
